config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "whats_for_lunch#index"

  resources :restaurants do
    resources :locations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :restaurant
  validates :address, :city, :province_code, :country_code, :postal_code, presence: true

  # this needs work... some sort of validation around country and province
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    scope :random, -> { order('RANDOM()').first }
    validates :name, presence: true
    has_many :locations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]

  def index
    @locations = Locations.all
  end

  def new
    @location = Location.new
    @restaurant = Restaurant.find(params[:restaurant_id]).id
  end

  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to new_location_path, notice: "Location #{@locaiton.name} succesfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @location = Location.find(params[:id])
  end

  def destroy
    Location.destroy(params[:id])
  end

  def location_params
    params.require(:location).permit(:address, :city, :country_code, :province_code, :postal_code, :restaurant_id)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to new_restaurant_path, notice: "Restaurant #{@restaurant.name} succesfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def destroy
    Restaurant.destroy(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description)
  end
end

app/controllers/whats_for_lunch_controller.rb
class WhatsForLunchController < ApplicationController
  def index
    @random_restaurant = Restaurant.random
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/whats_for_lunch_helper.rb
module WhatsForLunchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Whats for Lunch</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container-fuild">
      <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ">
              <%= link_to "Home", root_path, class: 'nav-link' %>
              <%= link_to "Restaurants", restaurants_path, class: 'nav-link' %>
              <%- if user_signed_in? %>
                <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %>
              <% else %>
                <%= link_to "Log In", new_user_session_path, class: 'nav-link' %>
                <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
              <% end %>
          </div>
          </div>
      </div>
      </nav>
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <div
          class="modal"
          tabindex="-1"
          data-controller="modal"
          data-action="turbo:frame-load->modal#open turbo:submit-end->modal#close"
        >
          <div class="modal-dialog">
            <div class="modal-content">
              <%= turbo_frame_tag "modal" %>
            </div>
          </div>
        </div>
        <%= yield %>
      </div>
      <div class="row">
        <div class="col">
          <footer>
            <p>Let your fate be decided by the algorithm.</p>
          </footer>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/locations/new.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="container">
    <h5 class="modal-header">Add Location</h2>
    <div class="modal-body">
      <%= form_with model: @location, url: restaurant_locations_url do |form| %>
        <div class="form-group required">
          <label for="name">Address</label>
          <%= form.text_field :address, class: 'form-control', type: 'text' %>
        </div>
        <div class="form-group">
          <label for="description">City</label>
          <%= form.text_field :city, class: 'form-control', type: 'text'%>
        </div>
        <div class="form-group">
          <label for="description">Country</label>
          <%= form.text_field :country, class: 'form-control', type: 'dropdown'%>
        </div>
        <div class="form-group">
          <label for="description">Province</label>
          <%= form.text_field :province, class: 'form-control', type: 'dropdown'%>
        </div>
        <div class="form-group">
          <label for="description">Postal Code</label>
          <%= form.text_field :postal_code, class: 'form-control', type: 'text'%>
        </div>
        <div class="form-group">
          <label for="description">Postal Code</label>
          <%= form.text_field :postal_code, class: 'form-control', type: 'dropdown'%>
          <%= form.collection_select(:restaurant_id, Restaurant.all, :id, :name, {:selected => @restaurant}) %>
        </div>
          <%= form.submit "Save", class: 'btn btn-primary', type: 'submit' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<div class="row">
  <div class="col">
    <h1>All Restaurants</h1>
  </div>
  <div class="col">
    <%= link_to "Add Restaurant", new_restaurant_path, class: 'btn btn-primary', style: 'float: right' %>
  </div>
</div>
<div class="row">
  <div class="col">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col"></th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <% @restaurants.each do |restaurant| %>
        <tr>
          <td scope="row"><%= restaurant.name %></td>
          <td><%= restaurant.description %></td>
          <td><%= link_to "Show", restaurant, class: 'btn btn-primary btn-sm' %></td>
          <td><%= link_to "Edit", edit_restaurant_path(restaurant), class: 'btn btn-primary btn-sm' %></td>
          <td><%= link_to "Destroy", restaurant, class: 'btn btn-primary btn-sm', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="row">
    <div class="col-7">
    <h2>Add Restaurant</h2>
    </div>
</div>
<div class="row">
  <div class="col-7">
    <%= form_with model: @restaurant do |form| %>
      <div class="form-group required">
        <label for="name">Name</label>
        <%= form.text_field :name, class: 'form-control' %>
        <small id="nameHelp" class="form-text text-muted">Required</small>
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <%= form.text_area :description, class: 'form-control', type: 'text' %>
        <small id="descriptionHelp" class="form-text text-muted">A brief description</small>
      </div>
        <%= form.submit "Save", class: 'btn btn-primary', type: 'submit' %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="row">
  <div class="col">
    <h1><%= @restaurant.name %></h1>
    <p><%= @restaurant.description %></p>
  </div>
</div>
<div class="row">
  <div class="col">
    <h2>Locations</h2>
  </div>
    <div class="col">
    <%= link_to "Add Location", new_restaurant_location_path(params[:id]), class: 'btn btn-primary', style: 'float: right', data: { turbo_frame: 'modal' } %>
  </div>
</div>
<div class="row">
  <div class="col">
     <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Address</th>
          <th scope="col">City</th>
          <th scope="col">Province</th>
          <th scope="col">Country</th>
          <th scope="col">Postal Code</th>
        </tr>
      </thead>
      <% @restaurant.locations.each do |location| %>
        <tr>
          <td scope="row"><%= location.address %></td>
          <td><%= location.city %></td>
          <td><%= location.province_code %></td>
          <td><%= location.country_code %></td>
          <td><%= location.postal_code %></td>
          <td><%= link_to "Edit", edit_location_path(location) %></td>
          <td><%= link_to "Destroy", location, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/whats_for_lunch/index.html.erb
    <div class="row">
        <div class="col border-bottom">
            <h1 class="display-1">You should eat at <span class="restaurant"><%= @random_restaurant.name %></span></h1>
        </div>
    </div>
    <div class="row purple-main">
        <div class="col">
            <div class="content-lunch">
                <p>I don't want that <%= link_to "give me another", root_path, class: "card card-small" %></p>
                <div class="card-container">
                    <a class="card" href="slack://channel?team=TT1T37BHD&id=CSNQD8KS7">
                    <span>Start a Lunch Train</span>
                    </a>
                    <a class="card" target="_blank" href="https://www.google.ca/maps/search/<%= @random_restaurant.name %>">
                    <span>Get Directions</span>
                    </a>
                    <a class="card" target="_blank" href="https://www.skipthedishes.com">
                    <span>Get it Delivered</span>
                    </a>
                </div>
            </div>
        </div>
    </div>